User.create!([
  {email: "nalnaji@berkeley.edu", encrypted_password: "$2a$10$3rpuWThu/NeDwxf2p381F.wI1cODTCd.AbwSj//GDc3fcrqETFi1G", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 11, current_sign_in_at: "2015-04-16 08:48:26", last_sign_in_at: "2015-04-16 08:42:02", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "Naseem Al-Naji", chats_id: 58, last_visited_chat: 58, last_buddy_poll_time: 1429174147},
  {email: "carlton@banks.com", encrypted_password: "$2a$10$nvgDhxbF1P5MawKo5LAxXOn3yPOOQYj2GROpvrQqR46l6p.9/8xzO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 20, current_sign_in_at: "2015-04-20 23:04:52", last_sign_in_at: "2015-04-16 21:23:15", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "Carlton Banks", chats_id: 70, last_visited_chat: 70, last_buddy_poll_time: 1429219661},
  {email: "naji247@gmail.com", encrypted_password: "$2a$10$n5sIzmMVpeQusN6RJyjeGuZQRGmbJ7.BWIY8AWJmig8lqBIU8fypW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2015-04-16 09:10:21", last_sign_in_at: "2015-04-16 09:03:55", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "Naseem Alnaji", chats_id: 74, last_visited_chat: 74, last_buddy_poll_time: 1429575660}
])
Chat.create!([
  {course_id: 1, location_id: 1},
  {course_id: 1, location_id: 2},
  {course_id: 2, location_id: 1},
  {course_id: 4, location_id: 1},
  {course_id: 1, location_id: 4},
  {course_id: 1, location_id: 3},
  {course_id: 2, location_id: 3},
  {course_id: 3, location_id: 4},
  {course_id: 5, location_id: 1},
  {course_id: 6, location_id: 5},
  {course_id: 1, location_id: 5},
  {course_id: 2, location_id: 2},
  {course_id: 2, location_id: 4},
  {course_id: 3, location_id: 3},
  {course_id: 5, location_id: 5},
  {course_id: 4, location_id: 4},
  {course_id: 1, location_id: 6},
  {course_id: 3, location_id: 2},
  {course_id: 1, location_id: 7},
  {course_id: 2, location_id: 5},
  {course_id: 2, location_id: 7},
  {course_id: 3, location_id: 1},
  {course_id: 5, location_id: 4},
  {course_id: 2, location_id: 6},
  {course_id: 5, location_id: 3},
  {course_id: 5, location_id: 2},
  {course_id: 6, location_id: 2},
  {course_id: 6, location_id: 4},
  {course_id: 6, location_id: 1},
  {course_id: 3, location_id: 5},
  {course_id: 3, location_id: 6},
  {course_id: 5, location_id: 6},
  {course_id: 7, location_id: 6},
  {course_id: 7, location_id: 4},
  {course_id: 6, location_id: 6},
  {course_id: 6, location_id: 7},
  {course_id: 7, location_id: 2},
  {course_id: 7, location_id: 3},
  {course_id: 7, location_id: 7},
  {course_id: 4, location_id: 5},
  {course_id: 5, location_id: 7},
  {course_id: 7, location_id: 5},
  {course_id: 12, location_id: 7},
  {course_id: 12, location_id: 12},
  {course_id: 17, location_id: 13},
  {course_id: 14, location_id: 13},
  {course_id: 16, location_id: 13},
  {course_id: 16, location_id: 9},
  {course_id: 16, location_id: 5},
  {course_id: 16, location_id: 11},
  {course_id: 9, location_id: 10},
  {course_id: 9, location_id: 11},
  {course_id: 9, location_id: 12},
  {course_id: 9, location_id: 9},
  {course_id: 13, location_id: 10},
  {course_id: 9, location_id: 7},
  {course_id: 15, location_id: 11},
  {course_id: 17, location_id: 11},
  {course_id: 15, location_id: 10},
  {course_id: 15, location_id: 9},
  {course_id: 17, location_id: 10},
  {course_id: 17, location_id: 7},
  {course_id: 16, location_id: 10},
  {course_id: 12, location_id: 13},
  {course_id: 12, location_id: 8},
  {course_id: 13, location_id: 12},
  {course_id: 13, location_id: 11},
  {course_id: 13, location_id: 13},
  {course_id: 17, location_id: 6},
  {course_id: 2, location_id: 13},
  {course_id: 2, location_id: 10},
  {course_id: 2, location_id: 12},
  {course_id: 17, location_id: 9},
  {course_id: 17, location_id: 12}
])
Course.create!([
  {name: "EE 20"},
  {name: "CS 169"},
  {name: "CS 186"},
  {name: "CS 189"},
  {name: "CS 164"},
  {name: "EE 40"},
  {name: "CS 170"},
  {name: "EE 141"},
  {name: "MATH 54"},
  {name: "MATH 55"},
  {name: "MATH 53"},
  {name: "MATH 16A"},
  {name: "MATH 16B"},
  {name: "MUSIC 20A"},
  {name: "PHILOS 107"},
  {name: "CS 194-5"},
  {name: "CS 195"}
])
Identity.create!([
  {user_id: 3, provider: "facebook", uid: "10206685843368941"}
])
Location.create!([
  {name: "Bechtel Library", lat: 0.0, long: 0.0, description: nil},
  {name: "Moffit Library", lat: 0.0, long: 0.0, description: nil},
  {name: "Student Learning Center", lat: 0.0, long: 0.0, description: nil},
  {name: "Doe Library", lat: 0.0, long: 0.0, description: nil},
  {name: "Unit 1", lat: 0.0, long: 0.0, description: nil},
  {name: "Unit 2", lat: 0.0, long: 0.0, description: nil},
  {name: "Unit 3", lat: 0.0, long: 0.0, description: nil},
  {name: "Free Speech Movement", lat: 0.0, long: 0.0, description: nil},
  {name: "Cafe Strada", lat: 0.0, long: 0.0, description: nil},
  {name: "Blue Door Cafe", lat: 0.0, long: 0.0, description: nil},
  {name: "Cafe Milano", lat: 0.0, long: 0.0, description: nil},
  {name: "Memorial Glade", lat: 0.0, long: 0.0, description: nil},
  {name: "Evans", lat: 0.0, long: 0.0, description: nil}
])
Message.create!([
  {chat_id: 2, user_id: 2, content: "meep"},
  {chat_id: 4, user_id: 1, content: "hmmm"},
  {chat_id: 4, user_id: 2, content: "Sup"},
  {chat_id: 4, user_id: 1, content: "LOL"},
  {chat_id: 5, user_id: 1, content: "Hey"},
  {chat_id: 5, user_id: 2, content: "PUSSY"},
  {chat_id: 5, user_id: 2, content: "Chris sucks"},
  {chat_id: 5, user_id: 1, content: "yeah i do"},
  {chat_id: 6, user_id: 2, content: "Yooo"},
  {chat_id: 6, user_id: 1, content: "HEY"},
  {chat_id: 11, user_id: 1, content: "hi"},
  {chat_id: 13, user_id: 1, content: "hi"},
  {chat_id: 14, user_id: 1, content: "hi"},
  {chat_id: 1, user_id: 1, content: "hello"},
  {chat_id: 1, user_id: 2, content: "hi"},
  {chat_id: 1, user_id: 1, content: "hi"},
  {chat_id: 1, user_id: 1, content: "hi"},
  {chat_id: 1, user_id: 1, content: "hello"},
  {chat_id: 1, user_id: 1, content: "hello"},
  {chat_id: 1, user_id: 1, content: "eitr"},
  {chat_id: 1, user_id: 1, content: "hi"},
  {chat_id: 1, user_id: 1, content: "hi"},
  {chat_id: 1, user_id: 1, content: "32e"},
  {chat_id: 1, user_id: 1, content: "3ri2j3"},
  {chat_id: 1, user_id: 1, content: "oejwo"},
  {chat_id: 1, user_id: 1, content: "oejwo"},
  {chat_id: 1, user_id: 1, content: "oejwo"},
  {chat_id: 1, user_id: 1, content: "porwijgef"},
  {chat_id: 1, user_id: 1, content: "peowijfw"},
  {chat_id: 1, user_id: 1, content: "wef"},
  {chat_id: 1, user_id: 1, content: "wefjwe"},
  {chat_id: 1, user_id: 1, content: "wu3fihe"},
  {chat_id: 1, user_id: 1, content: "weg"},
  {chat_id: 1, user_id: 1, content: "qoiefw"},
  {chat_id: 1, user_id: 1, content: "owi4g"},
  {chat_id: 1, user_id: 2, content: "You are a bitch"},
  {chat_id: 1, user_id: 1, content: "thanks man"},
  {chat_id: 1, user_id: 1, content: "woooo"},
  {chat_id: 11, user_id: 1, content: "hey"},
  {chat_id: 1, user_id: 1, content: "hey"},
  {chat_id: 16, user_id: 1, content: "hmmm"},
  {chat_id: 2, user_id: 1, content: "hi"},
  {chat_id: 2, user_id: 1, content: "sup"},
  {chat_id: 1, user_id: 1, content: "anyone here?"},
  {chat_id: 1, user_id: 1, content: "ewfw"},
  {chat_id: 5, user_id: 1, content: "qfeqfq"},
  {chat_id: 3, user_id: 1, content: "hi"},
  {chat_id: 2, user_id: 1, content: "hi"},
  {chat_id: 5, user_id: 2, content: "Niggaaaaaaa"},
  {chat_id: 5, user_id: 1, content: "sup"},
  {chat_id: 5, user_id: 1, content: "HEY BITCH"},
  {chat_id: 5, user_id: 2, content: "FUCK YOU"},
  {chat_id: 22, user_id: 1, content: "hi"},
  {chat_id: 18, user_id: 1, content: "sup"},
  {chat_id: 10, user_id: 1, content: "My name is Del"},
  {chat_id: 34, user_id: 1, content: "Sup sexy boy"},
  {chat_id: 37, user_id: 1, content: "Hey@"},
  {chat_id: 37, user_id: 1, content: "/ANYONE WORKING ON THE PS"},
  {chat_id: 33, user_id: 1, content: "eorifw"},
  {chat_id: 56, user_id: 1, content: "yes"},
  {chat_id: 57, user_id: 1, content: "yes"},
  {chat_id: 57, user_id: 1, content: "yes"},
  {chat_id: 57, user_id: 1, content: "yes"},
  {chat_id: 57, user_id: 1, content: "yes"},
  {chat_id: 58, user_id: 1, content: "yes"},
  {chat_id: 59, user_id: 1, content: "Yo"},
  {chat_id: 59, user_id: 1, content: "yo"},
  {chat_id: 59, user_id: 1, content: "you"},
  {chat_id: 59, user_id: 1, content: "you"},
  {chat_id: 59, user_id: 1, content: "yo"},
  {chat_id: 59, user_id: 1, content: "yo"},
  {chat_id: 59, user_id: 1, content: "yo"},
  {chat_id: 60, user_id: 1, content: "Yes"},
  {chat_id: 61, user_id: 2, content: "yo"},
  {chat_id: 61, user_id: 1, content: "ye"},
  {chat_id: 61, user_id: 1, content: "s"},
  {chat_id: 58, user_id: 2, content: "me"},
  {chat_id: 47, user_id: 1, content: "hey"},
  {chat_id: 67, user_id: 3, content: "yoooo"},
  {chat_id: 70, user_id: 3, content: "Yooooo"},
  {chat_id: 70, user_id: 2, content: "HEY"}
])
